#!/usr/bin/env python

import argparse
from subprocess import call

parser = argparse.ArgumentParser(description='Hook some hooks.')
parser.add_argument('--owner')
parser.add_argument('--repository')
parser.add_argument('--branch')
parser.add_argument('--commit')
args = parser.parse_args()


def say(message):
    call(['/usr/bin/say', message])


say('You have changes in the %s branch of %s owner by %s. The new commit hash is %s.' % (
    args.branch, args.repository, args.owner, args.commit
))
